#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path

FILENAME_RE = re.compile(r"^(?P<difficulty>[A-Za-z0-9]+)_(?P<id>\d+)\.sgf$")


def parse_filename(path):
    match = FILENAME_RE.match(path.name)
    if not match:
        return None
    return match.group("difficulty"), int(match.group("id"))


def collect_problems(input_dir):
    problems = []
    skipped = 0
    for path in sorted(input_dir.glob("*.sgf")):
        parsed = parse_filename(path)
        if not parsed:
            skipped += 1
            continue
        difficulty, problem_id = parsed
        sgf_text = path.read_text(encoding="utf-8")
        problems.append(
            {
                "id": problem_id,
                "difficulty": difficulty,
                "filename": path.name,
                "sgf": sgf_text,
            }
        )
    return problems, skipped


def build_js(problems):
    payload = json.dumps(problems, ensure_ascii=True, separators=(",", ":"))
    lines = [
        "// Auto-generated by scripts/build_gp_index.py",
        "// DO NOT EDIT MANUALLY",
        "(function (root) {",
        "  var problems = " + payload + ";",
        "  var byId = {};",
        "  for (var i = 0; i < problems.length; i += 1) {",
        "    var item = problems[i];",
        "    byId[String(item.id)] = item;",
        "  }",
        "  root.gpProblems = problems;",
        "  root.gpProblemsById = byId;",
        "})(",
        '  typeof window !== "undefined"',
        "    ? window",
        '    : typeof globalThis !== "undefined"',
        "      ? globalThis",
        "      : this",
        ");",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Build a JS index of GoProblems SGFs."
    )
    parser.add_argument(
        "--input-dir",
        default="gp",
        help="Folder containing SGF files (default: gp)",
    )
    parser.add_argument(
        "--output",
        default="gp/problems.js",
        help="JS output path (default: gp/problems.js)",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.exists():
        raise SystemExit(f"Input dir not found: {input_dir}")

    problems, skipped = collect_problems(input_dir)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_js(problems), encoding="utf-8")

    print(
        f"Wrote {len(problems)} problems to {output_path} "
        f"(skipped {skipped} files)."
    )


if __name__ == "__main__":
    main()
